name: Spack buildcache build

on:
  workflow_call:
  push:
  workflow_dispatch:
    inputs:
      fresh:
        type: boolean
        description: Create a fresh buildcache
        default: false

env:
  SPACK_BACKTRACE: 1

jobs:
  rebuild:
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Setup Spack
      uses: spack/setup-spack@5ab3c91bdefffffad9a7e45d1d156146afebb3a7 # v2.1.1

    - name: Find compilers
      run: spack -e . compiler find

    - name: Concretize (fresh)
      run: spack -e . -v concretize --fresh
      if: ${{ github.event.inputs.fresh == 'true' }}

    - name: Concretize (reuse)
      run: spack -e . -v concretize
      if: ${{ github.event.inputs.fresh == 'false' || github.event_name != 'workflow_dispatch' }}

    - name: Install
      run: |
        spack -e . env depfile -o Makefile
        make -Orecurse -j $(($(nproc) + 1))

    - name: Push packages and update index
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        spack -e . buildcache push -j $(($(nproc) + 1)) --base-image ubuntu:24.04 --update-index local-buildcache
      if: ${{ !cancelled() }}
